org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
ae2_version=15.2.1
ae2_version_range=[15.0.0,)
mod_id=compassrefresh
mod_name=AE2 Compass Refresh
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.konek101.compassrefresh
mod_authors=konek101
mod_description=Adds shift-right-click refresh functionality to the AE2 Meteorite Compass.
